### PR TITLE
Update pom.xml to use java 1.7

### PR DESCRIPTION
**Pull request by dpwspoon**
Updated source and target of gateway.client.java.common, and incremented minor version of component

### CODE REVIEW

**Comment by sanjay-saxena** [comment]
Android compliance level is 1.6. I am not sure if we can generically change the JDK version to 1.7 for clients.

**Comment by dpwspoon** [comment]
Okay, is it necessary for Android?  @brennangaunce email chain said earlier today that only 1.7+ was supported for server and client.  But I'm not sure if he was recalling Android.

**Comment by jfallows** [comment]
AFAIK our Android base platform is still 1.6-based.

**Comment by jfallows** [comment]
Btw, we could also remove this project since each child project can specify its Java dependency without needing to redefine the maven compiler plugin.
```
<properties>
  <maven.compiler.source>1.6</maven.compiler.source>
  <maven.compiler.target>1.6</maven.compiler.target>
</properties>
```
See the user property for each of http://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#source and http://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#target.

That might keep the pom inheritance chain a bit simpler and easier to understand, as well as making it straightforward to diverge from the common baseline when appropriate, such as the Java Applet Demo being based on 1.7 instead of 1.6 needed by Android.

**Comment by dpwspoon** [comment]
Agreed, this would probably be a fair amount of work as we could restructure the gateway inheritance as well.  I wonder where the best place to track such a story / tech-debt would be.  Or if we should just to it piecemeal.

**Comment by jfallows** [comment]
We could do it piecemeal, just to make sure it gets done. :smile: 

Btw, I don't think there are many child projects of gateway.client.java.common, so that would probably take less than an hour.

**Pull request closed without merging**
